### ISSUE TITLE
dynamically get bip115BlockHeight and its hash

### ISSUE THREAD

**Issue by vietvu-nguyen** [MingMing71/LearnZencashjs#1]
https://github.com/MingMing71/LearnZencashjs/blob/a0d4217f5bf680b4109cf6a7e9bb6e2ad0ad387b/src/index.js#L15

This is an old bip115BlockHeight. It won't work since the current block height of the blockchain is 599981. A proper way to to it is to get the current blockheight then minus an offset, recommended [150, 600].

**Comment by MingMing71** [comment]
Now, it's using 600030 and offset 150.
