### ISSUE TITLE
Get the transaction Id from your own address

### ISSUE THREAD

**Issue by vietvu-nguyen** [MingMing71/LearnZencashjs#2]
https://github.com/MingMing71/LearnZencashjs/blob/a0d4217f5bf680b4109cf6a7e9bb6e2ad0ad387b/src/index.js#L20

This transaction Id is not from your address. That is why it didn't work. Take one of these transaction Ids https://explorer-testnet.zensystem.io/address/ztqxUEzHwpxwSjKHm2AsFAxdbBbLZiYWVqX

**Comment by MingMing71** [comment]
I matched the txid. Thank you.
