### ISSUE TITLE
Send transaction error Code:-25

### ISSUE THREAD

**Issue by MingMing71** [MingMing71/LearnZencashjs#3]
Signed transaction:
```
010000000182d3bcce9329dd3b247743c40e601fca2ace814fb201db121fe6114cb940d32a000000006b483045022100f176c8f5033eaca721a161344c8d5e0b56c40265ef691a02079536bd96b1f05402205401df5aa5831f2494b69530056a2ca99d31470fcdf0590e4954b945e02249180121024dfee2c3bc507268551b1edd4d20006a111f36ccf742124ba8bda3fb33437d86ffffffff01a0860100000000003f76a9144a236e790364ef895241527b7138d6ade4b5fab888ac204d1409d322b9905332a8a2c10e42556667b5adfd9e966895c4044fa35005070003482709b400000000
```

I tried to send it on https://explorer-testnet.zen-solutions.io/tx/send
But it alway return code:
```
An error occured:
. Code:-25
```

**Comment by vietvu-nguyen** [comment]
Code: -25 occurs when you don't set an change address in recipients. Put your address as a change address in here. https://github.com/MingMing71/LearnZencashjs/blob/1b1cac6c1fddb1c71f07f4c070229e3b7022bcbe/src/index.js#L25

**Comment by MingMing71** [comment]
Is it's should be my address, not the address that i send money to?

**Comment by vietvu-nguyen** [comment]
that's true

**Comment by MingMing71** [comment]
Close due to fixed by correct input.
