### ISSUE TITLE
HD wallet

### ISSUE THREAD

**Issue by vietvu-nguyen** [MingMing71/LearnZencashjs#5]
https://github.com/MingMing71/LearnZencashjs/blob/f62de9b0ccb5a5a36cda7de0e52356d81deec1e5/src/index.js#L119

Here you directly generate private key from the seed. It doesn't work that way in multisig.

you have to drive from on HD node. like this
```
const seed = 'foo bar foo bar'
const hdNode = bip32.fromSeed(seed);
hdNode.derive(index).privateKey.toString('hex')

```

Take a look at: bitcoin-libjs bip32 fromSeed (use version 4.0.3) https://github.com/bitcoinjs/bip32/blob/2fca3348a8958a2d4c4d1b7a512c86e5296e40d5/src/bip32.js#L282

**Comment by MingMing71** [comment]
I committed new code using multiple HDwallet but still got error code: -25 message: ' '

**Comment by MingMing71** [comment]
Now mutisig is running using P2SH. I gonna close this issue.
